version: "3"

services:
  postgres:
    image: postgres:13.3-alpine
    volumes:
      - postgres_secure:/var/lib/postgresql/data
    networks:
      - secure-password
    environment:
      POSTGRES_DB: securepassword
      POSTGRES_USER: securepassword
      POSTGRES_PASSWORD: securepassword
      POSTGRES_PORT: 5432
    ports:
      - 5432:5432
    restart: on-failure

  nginx:
    image: nginx
    volumes:
      - ./nginx_data:/etc/nginx/nginx_data
    ports:
      - 80:80

  backend:
    build: .
    ports:
      - 8000:8000
    networks:
      - secure-password
    command:
      ./manage.py runserver 0.0.0.0:8080
    env_file:
      - .env
    environment:
      POSTGRES_DB: securepassword
      POSTGRES_USER: securepassword
      POSTGRES_PASSWORD: securepassword
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
    depends_on:
      - postgres
    restart: on-failure

  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    networks:
      - secure-password
    depends_on:
      - backend
    restart: on-failure

volumes:
  postgres_secure:
  nginx_data:

networks:
  secure-password:
    driver: bridge
