version: "3.2"

services:
  postgres:
    image: "postgres:13.3-alpine"
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - secure-password
    restart: on-failure

  nginx:
    image: nginx
    volumes:
      - ./nginx_data:/etc/nginx/nginx_data
    networks:
      - secure-password
    ports:
      - 80:80

  backend:
    build: .
    ports:
      - 8000:8000
    networks:
      - secure-password
    depends_on:
      - postgres

volumes:
  postgres_data:
  nginx_data:

networks:
  secure-password:
    driver: bridge