version: "3.3"

services:
  postgres:
    image: "postgres:13.3-alpine"
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - secure-password
    restart: on-failure

  nginx:
    image: nginx
    volumes:
      - ./nginx_data:/etc/nginx/nginx_data
    ports:
      - 80:80

  backend:
    build: .
    ports:
      - 8000:8000
    networks:
      - secure-password
    depends_on:
      - postgres
    restart: on-failure

  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    networks:
      - secure-password
    depends_on:
      - backend
    restart: on-failure

volumes:
  postgres_data:
  nginx_data:

networks:
  secure-password:
    driver: bridge
