version: "2.4"

services:
  postgres:
    image: "postgres:13.3-alpine"
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    restart: on-failure

volumes:
  postgres_data: